language: rust
sudo: required
addons:
  apt:
    packages:
      - libssl-dev
cache: cargo
rust:
  - stable
script:
  - cargo build --all-targets
  - cargo test --all-targets
after_success: |
  if [[ "$TRAVIS_RUST_VERSION" == stable ]]; then
    cargo install cargo-tarpaulin &&
    cargo tarpaulin --no-count --skip-clean --out Xml &&
    bash <(curl -s https://codecov.io/bash)
  fi