language: rust
sudo: required
addons:
  apt:
    packages:
      - libssl-dev
cache: cargo
rust:
  - stable
before_cache: |
  if [[ "$TRAVIS_RUST_VERSION" == stable ]]; then
    cargo install cargo-tarpaulin
  fi
script:
  - cargo build --all-targets
  - cargo test --all-targets
after_success: |
  if [[ "$TRAVIS_RUST_VERSION" == stable ]]; then
    cargo tarpaulin --out Xml
    bash <(curl -s https://codecov.io/bash)
  fi