[package]
name = "rust-mdd-solver"
version = "0.1.0"
authors = ["Xavier Gillard <xavier.gillard@uclouvain.be>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitset-fixed     = "0.1.0"
binary-heap-plus = "0.2.0"
fnv              = "1.0.6"

# parsing examples
regex = "1.3.3"
