[workspace]
members = [
    "ddo",
    "ddo-viz",
    #"py_ddo",
    #
    "xtask",
]

[profile.release]
lto              = 'fat'
panic            = 'abort'
opt-level        = 3
incremental      = true
